### PR TITLE
Sans coming soon

### PR DESCRIPTION
**Pull request by tboning**
Merge of the Coming Soon removed version into the main branch.

### CODE REVIEW

**Comment by jhurwitz** [comment]
Can you repush where 7716770 is the only commit, and not the other two?

**Comment by tboning** [comment]
Rebased with correct set of commits

**Comment by lfaraone** [comment]
lgtm, merging.

**Comment by jhurwitz** [comment]
@tboning, can you also delete dormbase/templates/comingSoon.html and dormbase/static/img/comingSoon.jpg?

**Pull request merged**
