### PR TITLE
Reorder .gitignore to make sense; add .virtualenv

### PR DESCRIPTION
**Pull request by achernya**

### CODE REVIEW

**Comment by jhurwitz** [comment]
LGTM. Do you want to push or should I?

**Comment by quentinmit** [comment]
What causes .virtualenv to come into existence? I feel like this should be done in local .git/info/exclude if people want that for editing, but not in the upstream project.

**Comment by jhurwitz** [comment]
We're (at some point soon) instructing users to use virtualenv, so won't everyone have that file soon?

**Comment by achernya** [comment]
That's what I personally called my environment, and I want to recommend that to users.

**Comment by quentinmit** [comment]
@jhurwitz Only if they name their virtualenv that and put it there. I personally recommend keeping your virtualenv entirely separate from your Git repo.

@achernya I would feel better about this if we actually provided a setup script for creating a development area that used it.

**Pull request merged**
