### PR TITLE
Basic guest list support

### PR DESCRIPTION
**Pull request by quentinmit**
This adds a basic guest list model and a UI for searching guest lists on the desk page.

### CODE REVIEW

**Comment by achernya** [comment]
When I try to import the test guests, I get

```
╰─$ python manage.py shell  
Python 2.7.3 (default, Nov  5 2012, 18:05:01) 
[GCC 4.2.1 Compatible Apple Clang 4.0 ((tags/Apple/clang-421.0.57))] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from dormbase.personal.populate import *
>>> import_test_guests()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/achernya/hackArea/dormbase/dormbase/../dormbase/personal/populate.py", line 21, in import_test_guests
    g = Guest(resident = resident,
UnboundLocalError: local variable 'resident' referenced before assignment
>>> 
```

**Comment by quentinmit** [comment]
That will happen if you have no residents in your database; populate those 
first.

--Quentin

**Comment by lfaraone** [comment]
This looks basically fine. The issues with the way the autocomplete works were identified in person and discussed as intentional pending further work.

**Comment by achernya** [comment]
Merged as 2c5e30b..e0c74a0.

**Pull request closed without merging**
