### PR TITLE
Update requirements, add getting started documentation

### PR DESCRIPTION
**Pull request by jhurwitz**
Updating documentation that we'll need for the hackathon. If possible, I'd like to get this merged ASAP so I can start emailing people about getting Dormbase set up before the hackathon.

### CODE REVIEW

**Comment by lfaraone** [comment]
Could you put this in a `README.md` so that it displays nicely in GitHub, etc? 

Also ==dehnert

**Comment by jhurwitz** [comment]
Given tboning's pull request that just came in, do we still need this file?

**Comment by lfaraone** [comment]
Having some sort of doc explaining wtf to do is generally good. README is the standard, so, maybe this specific pull request isn't what we want, but its a good idea / start

**Comment by dehnert** [comment]
Much of the stuff in this is not in Tom's pull request (eg, the settings changes), and vice-versa. I'm not really sure what to conclude from that, since I don't know Dormbase. (Also Tom's isn't quite ready to merge, but it seems close.)

**Comment by jhurwitz** [comment]
I pushed changes. You can re-review?

**Pull request merged**
