### PR TITLE
Fix README to be consistent with Wiki

### PR DESCRIPTION
**Pull request by nil3**

### CODE REVIEW

**Comment by jhurwitz** [comment]
Line wrapping is still all sorts of messed up.

**Comment by jhurwitz** [comment]
<nitpick> Can you remove the spaces at the ends of each line?

**Comment by jhurwitz** [comment]
A few of the wiki pages are out of date, but I can fix that separate from this commit.

Things I notice that still need to be changed: Code block (at the end) needs line breaks, and you say rebuild_index twice.

**Comment by jhurwitz** [comment]
@achernya - I think I did something wrong because https://github.com/dormbase/dormbase/commits/master doesn't say that I committed it. Can we chat so I can review the pull request process with you?

**Comment by achernya** [comment]
I see as having pushed it?

**Pull request merged**
